### ISSUE TITLE
this is very useful!

### ISSUE THREAD

**Issue by jondot** [gabrielmbmb/candle-holder#1]
Thanks, with this and candle, there's a good chance to replace `rust-bert`.
Will you be planning to be covering more [rust-bert](https://github.com/guillaume-be/rust-bert) pipelines?

**Comment by gabrielmbmb** [comment]
Hi @jondot, thanks!

Yes, my idea is at some point cover all the pipelines offered in https://github.com/huggingface/transformers + embeddings pipelines. Right now I'm implementing the ones I think are most used: text-classification, token-classification, text-generation, etc.
